import { retrieveAPIKey } from 'c/pexelsAPIKey';

describe('c-pexels-api-key', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        
        const apiKey = retrieveAPIKey();
        
        expect(apiKey).not.toBeNull();
    });
});